# Generated by Django 5.2.7 on 2025-10-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divine_Circle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojabooking',
            name='amount_paise',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
