# Generated by Django 5.2.7 on 2025-10-18 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divine_Circle', '0002_poojabooking_amount_paise_poojabooking_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PoojaSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('booked_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='Divine_Circle.poojaevent')),
            ],
            options={
                'ordering': ['event', 'start_time'],
                'unique_together': {('event', 'start_time')},
            },
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='Divine_Circle.poojaslot'),
        ),
    ]
