# Generated by Django 5.2.7 on 2025-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Divine_Circle', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='poojabooking',
            name='pooja_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='preferred_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='poojabooking',
            name='preferred_slot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
